- path: ${NODE_SCRIPTS_PATH}/init/registerTopology.sh
  permissions: "550"
  content: |
    #!/bin/bash

    if [[ $NODE_TYPE == block ]]; then
    echo "Cannot create relay on block node."
    return;
    fi

    BLOCK_NODE_IP_1="" # Preferably a floating IP

    while :; do
      case $1 in
        -ip1)
          BLOCK_NODE_IP_1=$2
        ;;
        *)
      break
      esac
      shift
    done


    if [ -z $BLOCK_NODE_IP_1 ]; then 
      echo "Enter block node IP address."
      read BLOCK_NODE_IP_1
    fi

    # for ELEMENT in "$BLOCK_NODE_IP_1"; do
    if [ -z $BLOCK_NODE_IP_1 ];
    then
    echo ""
    else
      if [[ $BLOCK_NODE_IP_1 =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]];
      then 
      echo ""
      else
        echo "$BLOCK_NODE_IP_1 is not a valid ip"
        return;
      fi
    fi
    # done

    DEFAULT_IOHK_RELAY="relays-new.cardano-${NODE_NETWORK}.iohk.io"
    [[ "${NODE_NETWORK}" = "mainnet" ]] && DEFAULT_IOHK_RELAY="relays-new.cardano-${NODE_NETWORK}.iohk.io" || DEFAULT_IOHK_RELAY="relays-new.cardano-${NODE_NETWORK}.iohkdev.io"


    if [ -z $BLOCK_NODE_IP_1 ]; then
    echo "No block node IP passed, using defaults"
    cat > $CONFIG_TOPOLOGY << EOF 
    {
        "Producers": [
          {
            "addr": "$DEFAULT_IOHK_RELAY",
            "port": 3001,
            "valency": 2
          }
        ]
      }
    EOF
    else
    echo "Block node IP passed, $BLOCK_NODE_IP_1"
    cat > $CONFIG_TOPOLOGY << EOF 
    {
        "Producers": [
          {
            "addr": "$BLOCK_NODE_IP_1",
            "port": ${NODE_PORT},
            "valency": 1
          },
          {
            "addr": "$DEFAULT_IOHK_RELAY",
            "port": 3001,
            "valency": 2
          }
        ]
      }
    EOF
    fi

    # Should write the block node ip to config here

    # Apply firewall settings
    sudo iptables -I INPUT -p tcp -m tcp --dport ${NODE_PORT} --tcp-flags FIN,SYN,RST,ACK SYN -m connlimit --connlimit-above 5 --connlimit-mask 32 --connlimit-saddr -j REJECT --reject-with tcp-reset
    sudo ufw allow from "$BLOCK_NODE_IP_1" to any port "${NODE_PORT}"

    # Complete Step
    sed -i "s#\Create Topology|Running#Create Topology|Complete#g" /home/cardano/.nodeSetup