- path: ${NODE_SCRIPTS_PATH}/init/create.sh
  permissions: "550"
  content: |
    #!/bin/bash

    if [[ $(du --apparent-size -B 1 /opt/cardano-node/db/immutable/ | cut -f1) -lt 3796516778 ]]; then
        echo "You need to sync the database before setting up the node. Make sure your db is updated and the node is synced."
        echo "If this is the first time starting your node, then this will take some time."
        return
    fi
    
    # If no block IP in the config, ask for it
    if [ -z $(cat ${NODE_HOME}/.config.json | jq '.blockIP') ]; then
      echo "Enter block node IP address."
      read _BLOCK_NODE_IP
      if [ ! -z $_BLOCK_NODE_IP ]; then
        . ${NODE_SCRIPTS_PATH}/updateConfigIP.sh "add" $_BLOCK_NODE_IP
      fi
    fi

    if [ ! -z $(cat ${NODE_HOME}/.config.json | jq '.blockIP') ]; then
      . ${NODE_SCRIPTS_PATH}/updateTopologyIP.sh
      . ${NODE_SCRIPTS_PATH}/topologyUpdater.sh
      sudo systemctl restart cardano-node
    fi