- path: ${NODE_SCRIPTS_PATH}/init/create.sh
  permissions: "550"
  content: |
    #!/bin/bash

    if [[ $(du --apparent-size -B 1 /opt/cardano-node/db/immutable/ | cut -f1) -lt 3530646460 ]]; then
        echo "You need to sync the database before setting up the node. Make sure your db is updated and the node is synced."
        echo "If this is the first time starting your node, then this will take some time."
        return
    fi
    
    # If no block IPs in the config, ask for them
    if [[ $(cat ${NODE_HOME}/.config.json | jq '.blockIPs | length') -eq 0 ]]; then
      echo "Enter block node IP address."
      read _BLOCK_NODE_IP_1
      if [ ! -z $_BLOCK_NODE_IP_1 ]; then
        . ${NODE_SCRIPTS_PATH}/updateConfigIP.sh "add" $_BLOCK_NODE_IP_1
      fi
    fi

    for IP in $(cat ${NODE_HOME}/.config.json | jq -r '.blockIPs[]' ); do
    if [ ! -z "$IP" ]; then
      . ${NODE_SCRIPTS_PATH}/updateTopologyIP.sh "add" $IP
    fi
    done

    . ${NODE_SCRIPTS_PATH}/topologyUpdater.sh

    sudo systemctl restart cardano-node