- path: ${NODE_SCRIPTS_PATH}/topologyPull.sh
  permissions: "550"
  content: |
    #!/bin/bash

    if [[ $(cat ${NODE_HOME}/.config.json | jq '.blockIPs | length') -eq 0 ]]; then
      echo "Enter block node IP address."
      read _BLOCK_NODE_IP_1
      if [ ! -z $_BLOCK_NODE_IP_1 ]; then
        . ${NODE_SCRIPTS_PATH}/updateConfigIP.sh "add" $_BLOCK_NODE_IP_1
      fi
    fi

    [[ "${NODE_NETWORK}" = "mainnet" ]] && DEFAULT_IOHK_RELAY="relays-new.cardano-mainnet.iohk.io" || DEFAULT_IOHK_RELAY="relays-new.cardano-testnet.iohkdev.io"

    customPeers="${DEFAULT_IOHK_RELAY}:3001:2"
    for IP in $(cat ${NODE_HOME}/.config.json | jq -r '.blockIPs[]' ); do
    if [ ! -z "$IP" ]; then
      customPeers="$IP:\${NODE_PORT}:1|${customPeers}"
    fi
    done

    pullTopologyResponseCode="$(curl -s ${CONFIG_TOPOLOGY} "https://api.clio.one/htopology/v1/fetch/?max=20&customPeers=\${customPeers}" | jq -r '.resultcode')"
    
    if [[ "$pullTopologyResponseCode" -eq 201 ]]; then
      pullTopologyProducers="$(curl -s ${CONFIG_TOPOLOGY} "https://api.clio.one/htopology/v1/fetch/?max=20&customPeers=\${customPeers}" | jq -r '.Producers')"
      echo "{
        \"Producers\": "$pullTopologyProducers"
      }" > $CONFIG_TOPOLOGY
    fi