- path: ${NODE_SCRIPTS_PATH}/topologyPull.sh
  permissions: "550"
  content: |
    #!/bin/bash

    if [ -z $(cat ${NODE_HOME}/.config.json | jq '.blockIP') ]; then
      echo "Enter block node IP address."
      read _BLOCK_NODE_IP
      if [ ! -z $_BLOCK_NODE_IP ]; then
        . ${NODE_SCRIPTS_PATH}/updateConfigIP.sh "add" $_BLOCK_NODE_IP
      fi
    fi

    [[ "${NODE_NETWORK}" = "mainnet" ]] && DEFAULT_IOHK_RELAY="relays-new.cardano-mainnet.iohk.io" || DEFAULT_IOHK_RELAY="relays-new.cardano-testnet.iohkdev.io"

    customPeers="${DEFAULT_IOHK_RELAY}:3001:2"
    BLOCK_NODE_IP=$(cat ${NODE_HOME}/.config.json | jq '.blockIP')
    if [ ! -z "$BLOCK_NODE_IP" ]; then
      customPeers="$BLOCK_NODE_IP:\${NODE_PORT}:1|${customPeers}"
    fi

    pullTopologyResponseCode="$(curl -s ${CONFIG_TOPOLOGY} "https://api.clio.one/htopology/v1/fetch/?max=20&customPeers=\${customPeers}" | jq -r '.resultcode')"
    
    if [[ "$pullTopologyResponseCode" -eq 201 ]]; then
      pullTopologyProducers="$(curl -s ${CONFIG_TOPOLOGY} "https://api.clio.one/htopology/v1/fetch/?max=20&customPeers=\${customPeers}" | jq -r '.Producers')"
      echo "{
        \"Producers\": "$pullTopologyProducers"
      }" > $CONFIG_TOPOLOGY
    fi