- path: ${NODE_SCRIPTS_PATH}/topologyUpdater.sh
  permissions: "550"
  content: |
    #!/bin/bash
    # shellcheck disable=SC2086,SC2034

    export CARDANO_NODE_SOCKET_PATH=${CARDANO_NODE_SOCKET_PATH}

    valency=1
    networkMagic=$(jq -r .networkMagic < ${CONFIG_SHELLY})
    blockNo=$(/usr/local/bin/cardano-cli query tip ${NODE_NETWORK_FLAG} | jq -r .block )
    nodeHostname=$(jq  '.hostname' < ${NODE_HOME}/.config.json)

    if [ ! -z nodeHostname ]; then
      _hostname="&hostname=$nodeHostname"
    else
      _hostname=''
    fi

    if [ ! -d ${NODE_LOG_PATH} ]; then
      mkdir -p ${NODE_LOG_PATH};
      sudo chown ${NODE_USER}:${NODE_USER} ${NODE_LOG_PATH}
    fi

    curl -s "https://api.clio.one/htopology/v1/?port=${NODE_PORT}&blockNo=${blockNo}&valency=${valency}&magic=${networkMagic}${_hostname}" | tee -a ${NODE_LOG_PATH}/topologyUpdaterLatest.json