- path: ${NODE_SCRIPTS_PATH}/topologyUpdater.sh
  permissions: "550"
  content: |
    #!/bin/bash
    # shellcheck disable=SC2086,SC2034

    CNODE_VALENCY=$(jq  '.relayIPs | length' < ${NODE_SCRIPTS_PATH}/.config.json) # for multi-IP hostnames
    NWMAGIC=$(jq -r .networkMagic < ${CONFIG_SHELLY})

    export CARDANO_NODE_SOCKET_PATH=${CARDANO_NODE_SOCKET_PATH}
    blockNo=$(/usr/local/bin/cardano-cli query tip ${NODE_NETWORK_FLAG} | jq -r .block )

    if [ "${NODE_HOSTNAME}" != "CHANGE ME" ]; then
      T_HOSTNAME="&hostname=${NODE_HOSTNAME}"
    else
      T_HOSTNAME=''
    fi

    if [ ! -d ${NODE_LOG_PATH} ]; then
      mkdir -p ${NODE_LOG_PATH};
      sudo chown ${NODE_USER}:${NODE_USER} ${NODE_LOG_PATH}
    fi

    curl -s "https://api.clio.one/htopology/v1/?port=${NODE_PORT}&blockNo=${blockNo}&valency=${CNODE_VALENCY}&magic=${NWMAGIC}${T_HOSTNAME}" | tee -a ${NODE_LOG_PATH}/topologyUpdaterLatest.json