- path: ${NODE_SCRIPTS_PATH}/init/cleanup.sh
  permissions: "550"
  content: |
    #!/bin/bash
    if [ -f ${NODE_PRIVATE_PATH}/deleg.cert ]; then
      rm ${NODE_PRIVATE_PATH}/deleg.cert
    fi
    if [ -f ${NODE_PRIVATE_PATH}/stake.cert ]; then
      rm ${NODE_PRIVATE_PATH}/stake.cert
    fi
    if [ -f ${NODE_PRIVATE_PATH}/pool.cert ]; then
      rm ${NODE_PRIVATE_PATH}/pool.cert
    fi