- path: ${NODE_SCRIPTS_PATH}/init/s3Sync.sh
  permissions: "550"
  content: |
    #!/bin/bash
    
    # If you already registered a pool - 
    # Use this to clone the necessary keys and certs from an S3 bucket. 

    echo "Enter AWS S3 Bucket:"
    read S3_CONFIG_PATH

    echo "Enter AWS Region:"
    read AWS_S3_REGION

    echo "Enter AWS Access Key ID:"
    read AWS_ACCESS_KEY_ID

    echo "Enter AWS Secret Access Key:"
    read AWS_SECRET_ACCESS_KEY

    export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
    export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
    export AWS_DEFAULT_REGION=$AWS_S3_REGION

    aws s3 cp "s3://$S3_CONFIG_PATH/node.cert" "${NODE_PRIVATE_PATH}/node.cert"
    aws s3 cp "s3://$S3_CONFIG_PATH/kes.skey" "${NODE_PRIVATE_PATH}/kes.skey"
    aws s3 cp "s3://$S3_CONFIG_PATH/vrf.skey" "${NODE_PRIVATE_PATH}/vrf.skey"
    aws s3 cp "s3://$S3_CONFIG_PATH/payment.addr" "${NODE_PRIVATE_PATH}/payment.addr"
    aws s3 cp "s3://$S3_CONFIG_PATH/pid.txt" "${NODE_PRIVATE_PATH}/pid.txt"

    unset AWS_ACCESS_KEY_ID
    unset AWS_SECRET_ACCESS_KEY
    unset AWS_DEFAULT_REGION