- path: ${NODE_SCRIPTS_PATH}/getTxInfo.sh
  permissions: "550"
  content: |
    #!/bin/bash

    if [ ! -f $NODE_PRIVATE_PATH/payment.addr ]; then
      echo "Missing payment.addr"
      return
    fi

    SLOT_NUMBER=$(cardano-cli query tip ${NODE_NETWORK_FLAG} | jq -r '.slot')

    cardano-cli query utxo \
        --address $(cat "$NODE_PRIVATE_PATH/payment.addr") \
        ${NODE_NETWORK_FLAG} > /tmp/fullUtxo.out

    tail -n +3 /tmp/fullUtxo.out | sort -k3 -nr > /tmp/balance.out

    tx_in=""
    total_balance=0
    while read -r utxo; do
        in_addr=$(awk '{ print $1 }' <<< "${utxo}")
        idx=$(awk '{ print $2 }' <<< "${utxo}")
        utxo_balance=$(awk '{ print $3 }' <<< "${utxo}")
        total_balance=$((${total_balance}+${utxo_balance}))
        tx_in="${tx_in} --tx-in ${in_addr}#${idx}"
    done < /tmp/balance.out
    txcnt=$(cat /tmp/balance.out | wc -l)
    
    rm -rf /tmp/balance.out 
    rm -rf /tmp/fullUtxo.out 

    echo "{ \"txIn\": \"${tx_in}\", \"txCnt\": \"${txcnt}\", \"balance\": \"${total_balance}\", \"slotNumber\": \"${SLOT_NUMBER}\" }"