- path: ${NODE_SCRIPTS_PATH}/info.sh
  permissions: "550"
  content: |
    #!/bin/bash

    SLOTS_PER_KES_PERIOD=$(cat $CONFIG_SHELLY | jq -r '.slotsPerKESPeriod')
    SLOT_NUMBER=$(cardano-cli query tip ${NODE_NETWORK_FLAG} | jq -r '.slot')
    KES_PERIOD=$(($SLOT_NUMBER / $SLOTS_PER_KES_PERIOD))
    KES_PERIOD_START=$KES_PERIOD


    MIN_POOL_COST=$(cat ${NODE_HOME}/params.json | jq -r .minPoolCost)

    echo -e '+--------------------------------------+'
    echo -e '|           Node Information           |'
    echo -e '+---------------------+----------------+'
    echo -e "| Slots per period    | $(printf "%14s" "$SLOTS_PER_KES_PERIOD") |"
    echo -e '+---------------------+----------------+'
    echo -e "| Slot number         | $(printf "%14s" "$SLOT_NUMBER") |"
    echo -e '+---------------------+----------------+'
    echo -e "| KES period          | $(printf "%14s" "$KES_PERIOD") |"
    echo -e "+---------------------+----------------+"
    echo -e "| Period Start        | $(printf "%14s" "$KES_PERIOD_START") |"
    echo -e '+---------------------+----------------+'
    echo -e "| Min Pool Cost       | $(printf "%14s" "$MIN_POOL_COST") |"
    echo -e '+---------------------+----------------+'



