- path: ${NODE_SCRIPTS_PATH}/rotateKES.sh
  permissions: "550"
  content: |
    #!/bin/bash
  
    nextStepMessage() {
    cat <<EOF

    KES has been generated, download them to your cold environment as a backup and so you can use them there.

    1.) Download the files from /home/${NODE_USER}/rotate-kes.zip to your cold environment. 

    Inside will be the following files:
    - kes.skey 
    - kes.vkey 
    - rotate-kes.sh

    2.) Move all files into the directory you plan on keeping/generating your keys with.
    3.) Execute 'rotate-kes.sh'. At this point many files will be generated.
    4.) Upload 'node.cert' from cold environment into /home/${NODE_USER}/ 

    EOF
    }

    slotNo=$(cardano-cli query tip ${NODE_NETWORK_FLAG} | jq -r '.slot')
    slotsPerKESPeriod=$(cat ${CONFIG_SHELLY} | jq -r '.slotsPerKESPeriod')
    kesPeriod=$((${slotNo} / ${slotsPerKESPeriod}))
    startKesPeriod=${kesPeriod}

    cardano-cli node key-gen-KES \
        --verification-key-file /tmp/kes.vkey \
        --signing-key-file /tmp/kes.skey


    # Generate file to download and run on cold machine
    if [ ! -f /home/${NODE_USER}/rotate-kes.sh ]; then
      cat > /home/${NODE_USER}/rotate-kes.sh << EOF 
        #!/bin/bash

        cardano-cli node issue-op-cert \
            --kes-verification-key-file kes.vkey \
            --cold-signing-key-file node.skey \
            --operational-certificate-issue-counter node.counter \
            --kes-period ${startKesPeriod} \
            --out-file node-$kesPeriod.cert

        echo "Upload node-$kesPeriod.cert into node /home/${NODE_USER}"
    EOF

      zip -q -j \
        /home/${NODE_USER}/rotate-kes.zip \
        /home/${NODE_USER}/rotate-kes.sh \
        /tmp/kes.skey \
        /tmp/kes.vkey

      rm -rf /home/${NODE_USER}/rotate-kes.sh
    fi

    # Start loop waiting for files
    RUN=true
    while $RUN
    do
    if [ -f /home/${NODE_USER}/node-$kesPeriod.cert ]; then
        mv /home/${NODE_USER}/node-$kesPeriod.cert ${NODE_PRIVATE_PATH}/node.cert
        mv /tmp/kes.skey ${NODE_PRIVATE_PATH}/kes.skey
        mv /tmp/kes.vkey ${NODE_PRIVATE_PATH}/kes.vkey
        rm -rf /home/${NODE_USER}/rotate-kes.zip
        RUN=false
    else
        sleep 2
    fi
    done
    # End loop waiting for files

    sudo systemctl restart cardano-node
