- path: ${NODE_SCRIPTS_PATH}/init/registerTopology.sh
  permissions: "550"
  content: |
    #!/bin/bash

    if [[ $(cat ${NODE_HOME}/.config.json | jq '.relayIPs | length') -eq 0 ]]; then
      _RELAY_NODE_IP_1=""
      RUN_RELAY_NODE_IP_1=true
      while $RUN_RELAY_NODE_IP_1
      do
      if [ ! -z $_RELAY_NODE_IP_1 ]; then
      . ${NODE_SCRIPTS_PATH}/updateConfigIP.sh "add" $_RELAY_NODE_IP_1
        RUN_RELAY_NODE_IP_1=false
      else 
        echo "Enter relay node 1 IP address."
        read _RELAY_NODE_IP_1
      fi 
      done
    fi

    echo "Enter relay node 2 IP address."
    read _RELAY_NODE_IP_2
    if [ ! -z $_RELAY_NODE_IP_2 ]; then
      . ${NODE_SCRIPTS_PATH}/updateConfigIP.sh "add" $_RELAY_NODE_IP_2
    fi

    . ${NODE_SCRIPTS_PATH}/updateTopologyIP.sh