- path: ${NODE_SCRIPTS_PATH}/init/manualSetupHelper.sh
  permissions: "550"
  content: |
    #!/bin/bash

    # This is used when splitting user data and setup scripts
    # runcmd only runs on boot, so we need another way to run those commands
    
    . ${NODE_SCRIPTS_PATH}/init/finish.sh