- sudo ufw allow 3001
- sudo iptables -I INPUT -p tcp -m tcp --dport ${NODE_RELAY_PORT} --tcp-flags FIN,SYN,RST,ACK SYN -m connlimit --connlimit-above 5 --connlimit-mask 32 --connlimit-saddr -j REJECT --reject-with tcp-reset