- path: ${NODE_SCRIPTS_PATH}/updateConfigIP.sh
  permissions: "550"
  content: |
    #!/bin/bash

    addItemToArray(){
    ipExists=$(cat ${NODE_HOME}/.config.json | jq '.'$1' | contains( ["'$2'"])')
    if ! $ipExists; then
        newValue=$(cat ${NODE_HOME}/.config.json | jq '.'$1' += ["'$2'"]')
        echo $newValue > ${NODE_HOME}/.config.json
    fi
    }

    removeItemFromArray(){
    ipExists=$(cat ${NODE_HOME}/.config.json | jq '.'$1' | contains( ["'$2'"])')
    if $ipExists; then
        newValue=$(cat ${NODE_HOME}/.config.json | jq '.'$1' -= ["'$2'"]')
        echo $newValue > ${NODE_HOME}/.config.json
    fi
    }

    addOrRemove="$1"
    ip="$2"
    updateConfigProperty="$3"

    if [ -z $addOrRemove ]; then 
      echo "add or remove IP from config?"
      read addOrRemove
    fi 

    if [ -z "$ip" ]; then 
      echo "Enter IP to $addOrRemove"
      read ip
    fi 

    if [ -z "$ip" ]; then 
      return
    fi 

    if [[ ! $ip =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
      echo "Invalid IP"
      return
    fi

    if [ -z $updateConfigProperty ]; then
      if [ ${NODE_TYPE} == "block" ]; then 
        updateConfigProperty="relay"
      elif [ ${NODE_TYPE} == "relay" ]; then 
        updateConfigProperty="block"
      fi
    fi

    if [ -z $updateConfigProperty ]; then
      echo "block or relay or whitelist?"
      read updateConfigProperty
    fi

    # If we are modifying the relay IPs
    if [ $updateConfigProperty == "relay" ]; then 
      if [ $addOrRemove == "add" ]; then
        addItemToArray relayIPs $ip
      fi
      if [ $addOrRemove == "remove" ]; then
        removeIItemFromArray relayIPs $ip
      fi
    fi

    # If we are modifying the block IP
    if [ $updateConfigProperty == "block" ]; then 
      if [ $addOrRemove == "remove" ]; then
        ip=""
      fi

      newValue=$(cat ${NODE_HOME}/.config.json | jq '.blockIP = "'$ip'"')
      echo $newValue > ${NODE_HOME}/.config.json
    fi

    # If we are modifying the whitelist IPs
    if [ $updateConfigProperty == "whitelist" ]; then 
      if [ $addOrRemove == "add" ]; then
        addItemToArray whitelistAccessIps $ip
      fi

      # Removing a whitelist IP
      if [ $addOrRemove == "remove" ]; then
        removeIItemFromArray whitelistAccessIps $ip
      fi
    fi