- path: ${NODE_SCRIPTS_PATH}/updateConfigIP.sh
  permissions: "550"
  content: |
    #!/bin/bash

    addOrRemove="$1"
    blockOrRelay="$2"
    ip="$3"

    if [ -z $addOrRemove ]; then 
      echo "add or remove IP from config?"
      read addOrRemove
    fi 

    if [ -z $blockOrRelay ]; then 
      echo "Updating IP of block or relay?"
      read blockOrRelay
    fi 

    if [ -z "$ip" ]; then 
      echo "Enter IP to $addOrRemove"
      read ip
    fi 

    if [ -z "$ip" ]; then 
      return
    fi 

    if [[ ! $ip =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
      echo "Invalid IP"
      return
    fi

    if [ $blockOrRelay == "relay" ]; then 
      # Adding a relay IP
      if [ $addOrRemove == "add" ]; then
        ipExists=$(cat ${NODE_HOME}/.config.json | jq '.relayIPs | contains( ["'$ip'"])')
        if ! $ipExists; then
            newValue=$(cat ${NODE_HOME}/.config.json | jq '.relayIPs += ["'$ip'"]')
            echo $newValue > ${NODE_HOME}/.config.json
        fi
      fi

      # Removing a relay IP
      if [ $addOrRemove == "remove" ]; then
        ipExists=$(cat ${NODE_HOME}/.config.json | jq '.relayIPs | contains( ["'$ip'"])')
        if $ipExists; then
            newValue=$(cat ${NODE_HOME}/.config.json | jq '.relayIPs -= ["'$ip'"]')
            echo $newValue > ${NODE_HOME}/.config.json
        fi
      fi
    fi


    if [ $blockOrRelay == "block" ]; then 
      if [ $addOrRemove == "remove" ]; then
        ip=""
      fi

      newValue=$(cat ${NODE_HOME}/.config.json | jq '.blockIP = "'$ip'"')
      echo $newValue > ${NODE_HOME}/.config.json
    fi